apiVersion: v1
kind: ConfigMap

metadata:
  name: devops-platform-api-config
  namespace: devops-platform

data:
  SERVICE_NAME: "azure-cloud-devops-api"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "kubernetes-local"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"