apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-platform-api
  namespace: devops-platform

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-platform-api

  template:
    metadata:
      labels:
        app: devops-platform-api

    spec:
      containers:
        - name: devops-platform-api
          image: azure-cloud-devops-api:local
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 5000

          envFrom:
            - configMapRef:
                name: devops-platform-api-config

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-platform-api-secret
                  key: REDIS_PASSWORD