apiVersion: v1
kind: Namespace
metadata:
  name: devops-platform
  labels:
    app.kubernetes.io/name: azure-cloud-devops-platform
    app.kubernetes.io/part-of: azure-cloud-devops-platform
    environment: dev